export const itemComponents = [
  {
    id: "frame_comp",
    title: "Frame",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    svg: "",
  },
  {
    id: "image_logo_comp",
    title: "Image Logo",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    src: "",
    imageEditingController: 0,
  },
  {
    id: "image_square_comp",
    title: "Image Square",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    src: "",
    imageEditingController: 0,
  },
  {
    id: "image_square_rounded_comp",
    title: "Image Square Rounded",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    rounded: 10,
    src: "",
    imageEditingController: 0,
  },
  {
    id: "image_circle_comp",
    title: "Image Circle",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    src: "",
    imageEditingController: 0,
  },
  {
    id: "container_square_comp",
    title: "Container Square",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    border: 0,
  },
  {
    id: "container_square_rounded_comp",
    title: "Container Square Rounded",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    border: 0,
    rounded: 10,
  },
  {
    id: "container_circle_comp",
    title: "Container Circle",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 100,
    height: 100,
    groupColor: 0,
    border: 0,
  },
  {
    id: "text_comp",
    title: "Text",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    text: "",
    fontSize: 12,
    fontFamily: "Poppins",
    fontWeight: "bold",
    textAlign: "center",
    textController: 0,
    groupColor: 0,
  },
];

// export const itemComponents = [
//   {
//     id: "frame_comp",
//     title: "Frame",
//   },
//   {
//     id: "image_logo_comp",
//     title: "Image Logo",
//   },
//   {
//     id: "image_square_comp",
//     title: "Image Square",
//   },
//   {
//     id: "image_square_rounded_comp",
//     title: "Image Square Rounded",
//   },
//   {
//     id: "image_circle_comp",
//     title: "Image Circle",
//   },
//   {
//     id: "container_square_comp",
//     title: "Container Square",
//   },
//   {
//     id: "container_square_rounded_comp",
//     title: "Container Square Rounded",
//   },
//   {
//     id: "container_circle_comp",
//     title: "Container Circle",
//   },
//   {
//     id: "text_comp",
//     title: "Text",
//   },
// ];
